cluster.name: "metrics_cluster"
node.name: "metrics-elasticsearch"
bootstrap.memory_lock: true
network.host: 0
http.port: 9200
thread_pool.write.queue_size: 100000
thread_pool.search.queue_size: 100000

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
