#!/bin/bash
BASE_PATH=$(dirname "${BASH_SOURCE}")
BASE_PATH=$(cd "${BASE_PATH}"; pwd)
source ${BASE_PATH}/funcs


# usage
usage() {
  echo "usage: $0 <start|stop|restart|logs|logsf> <mozart|grq|metrics|factotum|verdi|ci>" 2>&1
}


# get action
case "$1" in
start|stop|restart|logs)
  action=$1
  shift
  ;;
*)
  usage
  exit 1
esac
  

# get subsystem component
case "$1" in
mozart|grq|metrics|factotum|verdi|ci)
  comp=$1
  shift
  ;;
*)
  usage
  exit 2
esac


# run action
$action $comp $@
