version: '2.4'
services:
  mozart:
    hostname: mozart
    container_name: mozart
    image: hysds/mozart
    init: true
    user: "${ID}:${GID}"
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
      - "8888:8888"
      - "8898:8898"
      - "9001:9001"
    volumes:
      - "${HOME}/.sds/cluster/mozart/var/log/httpd:/etc/httpd/logs"
      - "${HOME}/.sds/cluster/mozart/log:/home/ops/mozart/log"
      - "${HOME}/.aws:/home/ops/.aws:ro"
      - "${HOME}/.netrc:/home/ops/.netrc:ro"
      - "${HOME}/.sds/cluster/mozart/etc/celeryconfig.py:/home/ops/mozart/etc/celeryconfig.py:ro"
      - "${HOME}/.sds/cluster/mozart/etc/supervisord.conf:/home/ops/mozart/etc/supervisord.conf:ro"
      - "${HOME}/.sds/cluster/mozart/etc/datasets.json:/home/ops/mozart/etc/datasets.json:ro"
      - "${HOME}/.sds/cluster/mozart/etc/job_status.template:/home/ops/mozart/etc/job_status.template:ro"
      - "${HOME}/.sds/cluster/mozart/etc/worker_status.template:/home/ops/mozart/etc/worker_status.template:ro"
      - "${HOME}/.sds/cluster/mozart/etc/task_status.template:/home/ops/mozart/etc/task_status.template:ro"
      - "${HOME}/.sds/cluster/mozart/etc/event_status.template:/home/ops/mozart/etc/event_status.template:ro"
      - "${HOME}/.sds/cluster/mozart/etc/indexer.conf:/home/ops/mozart/etc/indexer.conf:ro"
      - "${HOME}/.sds/cluster/mozart/etc/orchestrator_datasets.json:/home/ops/mozart/etc/orchestrator_datasets.json:ro"
      - "${HOME}/.sds/cluster/mozart/etc/orchestrator_jobs.json:/home/ops/mozart/etc/orchestrator_jobs.json:ro"
      - "${HOME}/.sds/cluster/mozart/etc/settings.cfg:/home/ops/mozart/etc/settings.cfg:ro"
      - "${HOME}/.sds/cluster/mozart/etc/utils.py:/home/ops/mozart/etc/job_creators/utils.py:ro"
      - "${HOME}/.sds/cluster/mozart/etc/utils_job.py:/home/ops/mozart/etc/job_creators/utils_job.py:ro"
    volumes_from:
      - redis
    links:
      - rabbitmq
      - redis
      - elasticsearch
  rabbitmq:
    image: hysds/rabbitmq
    hostname: mozart-rabbitmq
    container_name: mozart-rabbitmq
    user: "${ID}:${GID}"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "${HOME}/.sds/cluster/mozart/var/log/rabbitmq:/var/log/rabbitmq"
      - "${HOME}/.sds/cluster/mozart/var/lib/rabbitmq:/var/lib/rabbitmq"
      - "${HOME}/.sds/cluster/mozart/etc/rabbitmq-server:/etc/default/rabbitmq-server:ro"
      - "${HOME}/.sds/cluster/mozart/etc/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    environment:
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq
      - RABBITMQ_LOGS=$${RABBITMQ_LOG_BASE}/$${RABBITMQ_NODENAME}.log
      - RABBITMQ_SASL_LOGS=$${RABBITMQ_LOG_BASE}/$${RABBITMQ_NODENAME}-sasl.log
  redis:
    image: hysds/redis
    hostname: mozart-redis
    container_name: mozart-redis
    user: "${ID}:${GID}"
    ports:
      - "6379:6379"
    volumes:
      - "${HOME}/.sds/cluster/mozart/var/log/redis:/var/log/redis"
      - "${HOME}/.sds/cluster/mozart/var/lib/redis:/data/redis"
      - "${HOME}/.sds/cluster/mozart/etc/redis-config:/etc/redis.conf:ro"
    sysctls:
      #- vm.overcommit_memory=1
      #- vm.swappiness=0
      #- net.ipv4.tcp_sack=1
      #- net.ipv4.tcp_timestamps=1
      #- net.ipv4.tcp_window_scaling=1
      #- net.ipv4.tcp_congestion_control=cubic
      #- net.ipv4.tcp_syncookies=1
      #- net.ipv4.tcp_tw_recycle=1
      #- backlog setting
      #- net.ipv4.tcp_max_syn_backlog=102400
      - net.core.somaxconn=65535
      #- net.core.rmem_max=102400
      #- net.core.wmem_max=102400
      #- fs.file-max=102400
    command: [ "redis-server",
               "/etc/redis.conf" ]
  elasticsearch:
    image: hysds/elasticsearch
    hostname: mozart-elasticsearch
    container_name: mozart-elasticsearch
    user: "${ID}:${GID}"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "${HOME}/.sds/cluster/mozart/var/log/elasticsearch:/usr/share/elasticsearch/logs"
      - "${HOME}/.sds/cluster/mozart/etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${HOME}/.sds/cluster/mozart/etc/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro"
      - "${HOME}/.sds/cluster/mozart/var/lib/elasticsearch/data:/usr/share/elasticsearch/data"
    environment:
      - ES_HEAP_SIZE=${ES_HEAP_SIZE}m
      - MAX_LOCKED_MEMORY=unlimited
    command: [ "elasticsearch" ]
