version: '3.7'
services:
  grq:
    hostname: grq
    container_name: grq
    image: hysds/grq:${GRQ_TAG}
    init: true
    user: "${ID}:${GID}"
    ports:
      - "80:80"
      - "443:443"
      - "8878:8878"
    volumes:
      - "${HOME}/sciflo/log:/home/ops/sciflo/log"
      - "${HOME}/sciflo/log/httpd:/etc/httpd/logs"
      - "${HOME}/.aws:/home/ops/.aws:ro"
      - "${HOME}/.netrc:/home/ops/.netrc:ro"
      - "${HOME}/sciflo/etc/celeryconfig.py:/home/ops/sciflo/etc/celeryconfig.py:ro"
      - "${HOME}/sciflo/etc/supervisord.conf:/home/ops/sciflo/etc/supervisord.conf:ro"
      - "${HOME}/sciflo/etc/datasets.json:/home/ops/sciflo/etc/datasets.json:ro"
      - "${HOME}/sciflo/etc/grq2_settings.cfg:/home/ops/sciflo/etc/grq2_settings.cfg:ro"
      - "${HOME}/sciflo/etc/tosca_settings.cfg:/home/ops/sciflo/etc/tosca_settings.cfg:ro"
    links:
      - redis
      - elasticsearch
  redis:
    image: hysds/redis:${REDIS_TAG}
    hostname: grq-redis
    container_name: grq-redis
    user: "${ID}:${GID}"
    ports:
      - "6379:6379"
    volumes:
      - "${HOME}/sciflo/log/redis:/var/log/redis"
      - "${HOME}/sciflo/var/lib/redis:/data/redis"
      - "${HOME}/sciflo/etc/redis-config:/etc/redis.conf:ro"
    #########################################################
    # The following are commented out until docker supports
    # them becoming namespaced:
    # https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime
    # For now these are being set on the host via sysctld
    # using the ../config/10-hysds.conf file and the init.sh
    # script.
    #########################################################
    sysctls:
      #- vm.overcommit_memory=1
      #- vm.swappiness=0
      #- net.ipv4.tcp_sack=1
      #- net.ipv4.tcp_timestamps=1
      #- net.ipv4.tcp_window_scaling=1
      #- net.ipv4.tcp_congestion_control=cubic
      #- net.ipv4.tcp_syncookies=1
      #- net.ipv4.tcp_tw_recycle=1
      #- backlog setting
      #- net.ipv4.tcp_max_syn_backlog=102400
      - net.core.somaxconn=65535
      #- net.core.rmem_max=102400
      #- net.core.wmem_max=102400
      #- fs.file-max=102400
    ulimits:
      nofile:
          soft: 102400
          hard: 102400
    command: [ "redis-server",
               "/etc/redis.conf" ]
  elasticsearch:
    image: hysds/elasticsearch:${ELASTICSEARCH_TAG}
    hostname: grq-elasticsearch
    container_name: grq-elasticsearch
    user: "${ID}:${GID}"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "${HOME}/sciflo/log/elasticsearch:/usr/share/elasticsearch/logs"
      - "${HOME}/sciflo/etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
      - "${HOME}/sciflo/etc/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro"
      - "${HOME}/sciflo/var/lib/elasticsearch/data:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
          soft: -1
          hard: -1
      nofile:
          soft: 102400
          hard: 102400
    #########################################################
    # The following are commented out until docker supports
    # them becoming namespaced:
    # https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime
    # For now these are being set on the host via sysctld
    # using the ../config/10-hysds.conf file and the init.sh
    # script.
    #########################################################
    sysctls:
      #- vm.max_map_count=262144
      - net.core.somaxconn=65535
    environment:
      - ES_HEAP_SIZE=${ES_HEAP_SIZE}m
      - MAX_LOCKED_MEMORY=unlimited
    command: [ "elasticsearch" ]
